import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Muh Israjab DS
 */
public class login extends javax.swing.JFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    koneksiPoly k = new koneksiPoly();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        k.connect();
    }

     class user{
       int id;
       String level,nama_user,username,password;

        public user() {
            this.id = 0;
            this.level = "";
            this.nama_user = "";
            this.username = usernames.getText();
            this.password = passwords.getText();
        }
       
       
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        usernames = new javax.swing.JTextField();
        passwords = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        passwordlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1019, 615));
        getContentPane().setLayout(null);

        labelLogin.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Log In");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(430, 60, 160, 90);

        usernamelabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamelabel.setText("Username");
        getContentPane().add(usernamelabel);
        usernamelabel.setBounds(230, 190, 100, 20);

        usernames.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(usernames);
        usernames.setBounds(230, 220, 590, 40);

        passwords.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passwords);
        passwords.setBounds(230, 310, 590, 40);

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("BATAL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(320, 400, 140, 50);

        btnlogin.setBackground(new java.awt.Color(0, 0, 0));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(520, 400, 140, 50);

        passwordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Password ");
        getContentPane().add(passwordlabel);
        passwordlabel.setBounds(230, 280, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trans.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1, -4, 1020, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arelec.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-270, -20, 1290, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
            user u = new user();
        try {
            this.stat = k.getCon().prepareStatement("select * from user where "
                        + "username='"+u.username+"' and password='"+u.password+"';");
       this.rs = this.stat.executeQuery(); 
       //Dengan menggunakan pernyataan while (rs.next()), blok kode yang terdapat
       //di dalamnya akan terus diulang sampai tidak ada baris lain yang dapat diakses dari objek ResultSet.
        while (rs.next()){
            u.level = rs.getNString("level");
        }
        if(u.level == ""){
            JOptionPane.showMessageDialog(null, "User Tidak Terdaftar!");
        }else{
             // Switch di gunakan untuk memmilih suatu blok code yang di jalankan berdasarkan nilai true apa bila code yang ada di atas
             // Tidak sesuai maka code tersebut akan di abaikan dan blok code selanjutnya akan di ajalankan apabila sesuai dengan nilai case
             // yang di tentukan
            switch(u.level){
                case  "kasir":
                    Transaksi t = new Transaksi();
                    t.setVisible(true);
                   this.setVisible(false);   
                   break;
            } 
                    // SetVisible(true) berfungsi untuk menampilkan objeck pada layar apabila Objek telah di Set-Visible true
                    // SetVisible(False) berfungsi untuk menyembunyikan objek padaa layar apa bila objeck di  Set-Visible False 
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField passwords;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JTextField usernames;
    // End of variables declaration//GEN-END:variables
}
